version: '3'
services:
  db:
    image: postgres
    container_name: kollab-db
  kollab:
    build:
      context: .
      dockerfile: ./docker/Docker.server/Dockerfile
    image: kollab
    env_file: .env
    container_name: kollab
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:postgres
